### ISSUE TITLE
无法保存透明像素

### ISSUE THREAD

**Issue by Au3C2** [hellodk34/jpg2gif#1]
无法保存透明像素，透明像素会被转换成白色

**Comment by hellodk34** [comment]
@Au3C2 昨晚睡前才看到 issue。今天处理了一下，但是效果差强人意。这个问题我早前也意识到了，只是没有去处理，感谢你的提醒。请尝试 [release v1.1](https://github.com/hellodk34/jpg2gif/releases/tag/v1.1)

**Comment by Au3C2** [comment]
> 

谢谢您，我昨天摸鱼找到了一个python程序哈哈，贴在这里，各位自取

**Comment by hellodk34** [comment]
@Au3C2  贴在哪里了？

**Comment by hellodk34** [comment]
@Au3C2 看到了，非常感谢分享！

**Comment by Au3C2** [comment]
> @Au3C2 贴在哪里了？

敲快了还没编辑完就发出去了，重新编辑了下
