### ISSUE TITLE
最近在用的时候又发现两个小问题

### ISSUE THREAD

**Issue by Au3C2** [hellodk34/jpg2gif#2]
1.程序会把图片里的白色像素全部变成透明像素；
2.无法转换动态的png图像。

我找到一个比较完美的api可以解决这个问题：[yukinarit](https://github.com/yukinarit)/[apnggif](https://github.com/yukinarit/apnggif)

**Comment by hellodk34** [comment]
@Au3C2 

> 无法转换动态的png图像

这个程序不支持 gif 图转换的，可以看看 https://github.com/ed-asriyan/tgs-to-gif (readme 里提到了)。tg 的动图一般是体积更小的 webm 图像，实现的话可以通过获取源文件再转换成 gif。

---

> 程序会把图片里的白色像素全部变成透明像素

用上一个版本可以解决这个问题。 https://github.com/hellodk34/jpg2gif/releases/tag/v1.0
