### ISSUE TITLE
gif质量太差

### ISSUE THREAD

**Issue by SliverKeigo** [hellodk34/jpg2gif#3]
![image](https://github.com/hellodk34/jpg2gif/assets/112426853/dd6c25d3-a5fd-418f-95de-702e8101dd47)

**Comment by SliverKeigo** [comment]
已提交pr  https://github.com/hellodk34/jpg2gif/pull/5

**Comment by hellodk34** [comment]
这个黑色色块有可能是V2的jar包生成的效果。为了支持alpha通道导致的。换 V1 就好了
